# Generated by Django 3.1.7 on 2021-04-12 11:59

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20210412_0617'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='created_date',
            field=models.DateTimeField(default=datetime.datetime(2021, 4, 12, 11, 59, 4, 631102, tzinfo=utc)),
        ),
    ]
